POST http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIxIiwiaWQiOiI2MmM1OTg2MDQxOTA2MjA0YWZkYThmYWIiLCJpYXQiOjE2NTcyMzYzNTR9.OGCYeA63o7Va_TROvLk09f7qHlNTp9VSPhEbn3IqoYc

{
    "title": "Blog of user",
    "author": "user1",
    "url": "http",
    "likes": 0
}